# Generated by Django 2.2.1 on 2019-05-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_num', models.CharField(max_length=256)),
                ('question', models.CharField(max_length=256)),
                ('fi_answer', models.TextField()),
                ('se_answer', models.TextField()),
                ('th_answer', models.TextField()),
                ('fo_answer', models.TextField()),
                ('fv_answer', models.TextField()),
                ('correct_answer', models.CharField(max_length=256)),
            ],
        ),
    ]
